<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AutoClickerV1</AssemblyName>
    <RootNamespace>AutoClickerV1</RootNamespace>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

</Project>
