name: Build Auto Clicker

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        platform: [x86, x64]

    steps:

      # دریافت سورس پروژه
      - name: Checkout
        uses: actions/checkout@v4

      # نصب .NET SDK مورد نیاز برای Build پروژه
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      # Restore
      - name: Restore
        run: dotnet restore AutoClickerV1.csproj

      # Build نسخه 32 یا 64 بیتی
      - name: Build
        run: >
          dotnet build AutoClickerV1.csproj
          -c Release
          --no-restore
          /p:PlatformTarget=${{ matrix.platform }}

      # ذخیره فایل خروجی
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoClicker-${{ matrix.platform }}
          path: bin/Release/net48/
